---
- name: Add api systemd unit file
  ansible.builtin.template:
    src: container-api.service
    dest: '/home/{{ g_user }}/.config/systemd/user/container-{{ project_name }}-api.service'
    owner: '{{ g_user }}'
    mode: '0644'
  notify:
    - Restart API service

- name: Add ui systemd unit file
  ansible.builtin.template:
    src: container-ui.service
    dest: '/home/{{ g_user }}/.config/systemd/user/container-{{ project_name }}-ui.service'
    owner: '{{ g_user }}'
    mode: '0644'
  notify:
    - Restart UI service

- name: Clone repo
  ansible.builtin.git:
    repo: "git@github.com:acbilson/{{ repo_name }}.git"
    dest: "{{ g_src_path }}/{{ repo_name }}"
    depth: 1
    single_branch: true
    version: main
    key_file: '{{ g_mnt_path }}/git/git_rsa'
  become_user: '{{ g_user }}'

- name: Build the API Podman image
  containers.podman.podman_image:
    name: '{{ image_name }}-api:latest'
    path: '{{ g_src_path }}/{{ repo_name }}/api'
    state: build
    build:
      format: docker
  become_user: '{{ g_user }}'
  notify:
    - Restart API service

- name: Build the UI Podman image
  containers.podman.podman_image:
    name: '{{ image_name }}-ui:latest'
    path: '{{ g_src_path }}/{{ repo_name }}/ui'
    state: build
    build:
      format: docker
  become_user: '{{ g_user }}'
  notify:
    - Restart UI service

- name: Create db volume directories
  ansible.builtin.file:
    path: '{{ db_root }}'
    state: directory
    owner: '{{ g_user }}'
    mode: '0755'

- name: Enable API service
  ansible.builtin.systemd:
    name: 'container-{{ project_name }}-api'
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  become_user: '{{ g_user }}'

- name: Enable UI service
  ansible.builtin.systemd:
    name: 'container-{{ project_name }}-ui'
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  become_user: '{{ g_user }}'

- name: Create a UI log directory
  ansible.builtin.file:
    path: '/var/log/nginx/{{ project_name }}-ui'
    state: directory
    mode: '0755'

- name: Add Nginx config
  ansible.builtin.template:
    src: nginx.conf
    dest: '/etc/nginx/sites-available/{{ project_name }}.conf'
    mode: '0644'
  notify:
    - Restart nginx

- name: Enable proxy
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/{{ project_name }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ project_name }}.conf'
    state: link
