---
project_name: skyler-counseling
repo_name: skyler-counseling
image_name: localhost/acbilson/skyler-counseling
server_name: "skyler.{{ g_host }}"
exposed_port: 7250

static_root: /srv/skyler-counseling/static
db_root: /srv/skyler-counseling/db

# the static host is automatically prepended
static_url: "static/"

admin_user: "{{ VAULT_DJANGO_ADMIN_USER }}"
admin_password: "{{ VAULT_DJANGO_ADMIN_PASSWORD }}"
session_secret: "{{ VAULT_DJANGO_SESSION_SECRET }}"
